[package]
name = "papercraft"
version = "0.1.0"
authors = ["Maxwell Anderson <zaechus@proton.me>"]
edition = "2021"

[dependencies]
bracket-lib = { version = "0.8", features = ["serde", "threaded"]}
legion = "0.4"
